Repository AY2223S1-CS2103-F14-2/tp, pull requests merged in 2022-11, with the labels that each got.

#192 Update information in deeyonn.md
  docs/team/deeyonn.md
Labels: priority.Low, severity.Low

#248 Modify Gender.java to store gender as lower-case
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Gender.java
Labels: priority.Medium, severity.Low

#256 Edit UG duplicate check message to be clearer
  docs/UserGuide.md
Labels: priority.Low, type.DocumentationBug

#261 Add PPP and DG
  docs/DeveloperGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
  docs/images/ExportSequenceDiagram.png
  docs/team/cliftonfelix.md
Labels: type.Enhancement, priority.High

#259 Fix Incorrect JSON Format for Export
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckoutCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: type.Bug, priority.High

#252 Remove parseCap method in JsonAdaptedPerson.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: type.Enhancement

#265 Fix UG Bug: Make multiple field search feature clearer in UG
  docs/UserGuide.md
Labels: priority.High, severity.Medium, type.DocumentationBug

#260 Add JUnit tests for StringUtil#splitByWhiteSpace
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: type.Bug, priority.Medium, severity.Low

#257 Readjust CAP constraints
  src/main/java/seedu/address/model/person/Cap.java
  src/test/java/seedu/address/model/person/CapTest.java
Labels: type.Bug

#258 Update UG for Email and Cap field
  docs/UserGuide.md
Labels: type.DocumentationBug

#269 Update deeyonn.md and DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/team/deeyonn.md
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: priority.Medium, severity.Low

#273 Update DG and PPP for Daniel
  docs/DeveloperGuide.md
  docs/team/lulucopter.md
Labels: type.Chore, priority.High

#271 Change App Name and Version in MainApp
  src/main/java/seedu/address/MainApp.java
Labels: priority.Low

#275 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/UiClassDiagram.png
  docs/images/ViewSequenceDiagram.png
  docs/images/annotatedGui.png
  docs/images/guiDesignConsideration1.png
  docs/images/guiDesignConsideration2.png
Labels: type.Chore

#276 Update PPP for Jessica
  docs/team/maryjess.md
Labels: type.Chore

#264 Fix bug with FindCommandParser when empty search values are given
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/commons/util/CollectionUtilTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High, severity.Low, type.FunctionalityBug

#267 Reject invalid CAP inputs
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Cap.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/CapTest.java
Labels: type.Bug

#283 Add use case for checkout feature in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.Low

#288 Fix Use Case and underline in DG
  docs/DeveloperGuide.md
Labels: priority.High

#294 Find: Fixes all bugs related to cap search
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/commons/util/CollectionUtilTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High, severity.Medium, type.FunctionalityBug

#295 Find bug: invalid prefix
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High, severity.Medium, type.FunctionalityBug

#296 Add page breaks accordingly to make UG&DG pdf nicer to read
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Chore, severity.VeryLow

#298 Edit UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High
