Repository AY2223S1-CS2103-F14-2/tp, pull requests merged in 2022-10, with the labels that each got.

#100 Refine tag parameter for InternConnect
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.High

#101 Add Gender Class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/GenderTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#102 Add CAP class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Cap.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/CapTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#108 Modify PREFIX_ADDRESS in CliSyntax.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: priority.Medium

#107 Add Major Class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Major.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/MajorTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#112 Update PREFIX_PHONE and PREFIX_EMAIL in CliSyntax
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: type.Enhancement, priority.Medium

#149 Update DG to include View Feature
  docs/DeveloperGuide.md
Labels: type.Chore, priority.Medium

#134 Modify DeveloperGuide.md to include branching
  docs/DeveloperGuide.md
  docs/images/BranchState0.png
  docs/images/BranchState1.png
  docs/images/BranchState2.png
Labels: type.Chore, priority.Medium, severity.Low

#158 Update DG to include proposed additions to the existing find command
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#147 Length Limit for Several Fields
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/job/Id.java
  src/main/java/seedu/address/model/job/Title.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Major.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/University.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/job/IdTest.java
  src/test/java/seedu/address/model/job/TitleTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/MajorTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/UniversityTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Enhancement, priority.Medium

#138 Fix upper and lower case duplicate issues for Name and Email
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/SamePersonPredicateTest.java
Labels: type.Bug, severity.High

#167 Change Job Title REGEX
  src/main/java/seedu/address/model/job/Title.java
  src/test/java/seedu/address/model/job/TitleTest.java
Labels: priority.Low

#136 Add Message Specificity
  src/main/java/seedu/address/model/job/Id.java
  src/main/java/seedu/address/model/job/Title.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Enhancement, priority.Low

#168 Shorten CLI Syntax for fields
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Bug, priority.High, severity.Low

#166 Fix Bugs when User Manually Edits JSON file
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, priority.Medium

#135 Export Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/storage/Storage.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement, priority.High

#143 Refine View Feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/intern_connect.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/PersonViewCard.fxml
  src/main/resources/view/PersonViewPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: type.Enhancement, type.Bug, priority.High

#172 Edit index.md
  docs/index.md
Labels: type.Enhancement, priority.Low

#176 Update Ui.png
  docs/images/Ui.png
Labels: type.Chore, priority.Low

#175 Modify EditCommand to display edited person after edit
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.Medium, severity.Low

#179 Modify UserGuide.md to include checkout feature
  docs/UserGuide.md
Labels: priority.High, severity.Low

#184 Update DG with sequence diagram for FindCommand
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
Labels: type.Chore, priority.Medium

#182 Upgrade find functionality to include multiple by field search
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/predicates/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/CapContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/GenderContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/GraduationDateContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/JobIdContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/JobTitleContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/ListOfContainsKeywordsPredicates.java
  src/main/java/seedu/address/model/person/predicates/MajorContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/SamePersonPredicate.java
  src/main/java/seedu/address/model/person/predicates/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/UniversityContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/CollectionUtilTest.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/SamePersonPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/CapContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/GenderContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/GraduationDateContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/JobIdContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/JobTitleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/ListOfContainsKeywordsPredicatesTest.java
  src/test/java/seedu/address/model/person/predicates/MajorContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/UniversityContainsKeywordsPredicateTest.java
Labels: priority.High

#185 Change exportDisplayedList Method to be Non-Static
  docs/DeveloperGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
  docs/images/ExportSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckoutCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: type.Enhancement, priority.Low

#188 Fix various formatting issues in UserGuide.md
  docs/UserGuide.md
Labels: priority.High, severity.Low

#191 Update UG formatting: date
  docs/UserGuide.md
Labels: priority.Low
